services:
  postgres:
    image: postgres:16-alpine
    container_name: ivb-collection
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ivb-collection
    ports:
      - '5445:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
